# paste config here
# https://config.travis-ci.com/explore
# https://docs.travis-ci.com/user/languages/java/

# https://docs.travis-ci.com/user/languages/java/
language: java
jdk: openjdk8



# https://docs.travis-ci.com/user/notifications#Configuring-email-notifications
#notifications:
#  email: false